import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// Define Font

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Define Metadata e.g. description, title etc.

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// The name `RootLayout` does not matter.
// What is matter is `export default function ...`
// children is the child component, such that all page.tsx 
// inside sub directory following the common layout of layout.tsx.
// It is possible to create layout.tsx inside subdirectory,
// which overwrite layout of page.tsx inside the subdirectory where it belong to.

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
