import copy

import cv2
import numpy as np

from img_process.contour import get_contours, sort_contours
from img_process.utility import check_img, get_size, rgb_img
from include.img_process import img_process
from include.img_process_gray import img_process_gray
from include.img_process_rgb import img_process_rgb
from include.ocr_config import ocr_config
from ocr.save_text import save_text
from utility.utility import get_options

'''
Attribute

NAME        TYPE                DESCRIPTION
origin_img  img_process_rgb     original img image
marked_img  img_process_rgb     origin_img with the images of boxes (self.boxes)
dilate_img  img_process_gray    dilate image for getting the format of the text
all_boxes   tuple               array of all boxes generated by get_contours(img=self.dilate_img.img)
boxes       list                selected boxes from all_boxes, filtered by select_boxes
'''

class boxes_img:
    def __init__(self, 
                img: img_process| np.ndarray | str,
                thresh_px: int = 0,
                kernel: np.ndarray = np.ones(shape=(2, 30)),
                ksize: int = 9):
        if type(img) == img_process:
            img:np.ndarray = img.img
        elif type(img) == str:
            img:np.ndarray = cv2.imread(filename=img)
            if img is None:
                raise ValueError(f"Error: The file at path '{img}' could not be loaded.")
        elif type(img) == np.ndarray:
            img:np.ndarray = check_img(img)
        else:
            raise TypeError("Error: Input img must be img_process, np.ndarray or str")
        self.origin_img:img_process_rgb = img_process_rgb(img = rgb_img(img))
        self.marked_img:img_process_rgb = copy.deepcopy(self.origin_img)
        img:img_process_gray = img_process_gray(img=img)
        img.contour_img(
            thresh_px=thresh_px,
            kernel=kernel,
            ksize=ksize)
        self.dilate_img:img_process_gray = img
        self.all_boxes:tuple = get_contours(img=self.dilate_img.img)
        self.boxes = []

#-----------------------------------------------------------------------------------------

    # Get selected box as self.boxes from self.all_boxes filtered by this function.
    def select_boxes(
            self, 
            min_w:int = 0,
            max_w:int|None = None,
            min_h:int = 0,
            max_h:int|None = None,
            ) -> None:
        min_w = get_size(size=min_w, maxval=self.marked_img.img.shape[1])
        min_h = get_size(size=min_h, maxval=self.marked_img.img.shape[0])
        max_w = get_size(size=max_w, maxval=self.marked_img.img.shape[1],default_size=self.marked_img.img.shape[1])
        max_h = get_size(size=max_h, maxval=self.marked_img.img.shape[0],default_size=self.marked_img.img.shape[0])
        self.all_boxes = get_contours(img=self.dilate_img.img)
        self.boxes = []
        for i in self.all_boxes:
            if ((i[2] > min_w and i[3] > min_h) 
                and (i[2] < max_w and i[3] < max_h)):
                self.boxes.append(i)

#-----------------------------------------------------------------------------------------

    def column_boxes(self,vertical:bool = False):
        for i in self.boxes:
            print(i)

#-----------------------------------------------------------------------------------------

    # Sort the get_contours(img) based on x, y, width, height and size, using this function.
    '''
available `method` options
-   0 = x
-   1 = y
-   2 = width
-   3 = height
-   4 = size
    '''
    def sort_boxes(self, reverse: bool = False, method: int = 4)->None:
        self.boxes = sort_contours(contour=self.boxes, reverse=reverse, method=method)

#-----------------------------------------------------------------------------------------

    # Show the original img image with the image of selected box (self.boxes)
    def show_boxes(self,
            rgb:list[int]|int|None = None, title:str="boxes_img.show_boxes()"
            ) -> None:
        self.marked_img = copy.deepcopy(self.origin_img)
        for i in self.boxes:
            self.marked_img.rectangle(rgb=rgb,x=i[0], y=i[1], w=i[2], h=i[3])
        self.marked_img.show(title=title)

#-----------------------------------------------------------------------------------------

    # Get multiple images as array of image, based on self.boxes.
    def get_imgs(self, mode:int = 0) -> list[img_process_gray]|list[img_process_rgb]|list[np.ndarray]:
        message = """
-------------------------------------------------------------------------------------------
include/boxes_img.py/class boxes_img/def get_imgs()

def get_imgs(self, mode:int = 0) -> list[img_process_gray]|list[img_process_rgb]|list[np.ndarray]:
# This function return the lists of image based on `mode` option and self.boxes

available `mode` options
-   0 = np.ndarray
-   1 = img_process_rgb
-   2 = img_process_gray
-------------------------------------------------------------------------------------------
"""
        mode = get_options(input=mode,input_options=[0,1,2],message=message)
        out_img_arr = []
        for i in self.boxes:
            x, y, w, h = cv2.boundingRect(i)
            out_img = self.origin_img.img[y:y + h, x:x + w]
            if mode == 1:
                out_img = img_process_rgb(img = out_img)
            elif mode == 2:
                out_img = img_process_gray(img = out_img)
            out_img_arr.append(out_img)
        return out_img_arr

#-----------------------------------------------------------------------------------------

    # Save multiple images as array of image, based on self.boxes.
    def save_boxes(self,path: list[str] | str = ["img", "img_out", "jpg"]) -> None:
        count = 0
        if isinstance(path, str):
            path = ["img", path, "jpg"]
        for i in self.boxes:
            x, y, w, h = cv2.boundingRect(i)
            out_img = self.origin_img.img[y:y + h, x:x + w]
            out_img = img_process_rgb(img = out_img)
            count_stars = str(count)
            if count < 10:
                count_stars = '0' + count_stars
            out_img.save_img(path=[path[0], path[1]+"_" + count_stars, path[2]])
            count += 1

#-----------------------------------------------------------------------------------------

    # Update dilate_img using img_process_gray.contour_img method
    def update_dilate_img(self,                
                thresh_px: int = 0,
                kernel: np.ndarray = np.ones(shape=(2, 30)),
                ksize: int = 9) -> None:
        self.marked_img = copy.deepcopy(self.origin_img)
        img = img_process_gray(img = copy.deepcopy(self.origin_img.img))
        img = img_process_gray(img=img)
        img.contour_img(
            thresh_px=thresh_px,
            kernel=kernel,
            ksize=ksize)
        self.dilate_img = img
        self.all_boxes = get_contours(img=self.dilate_img.img)
        self.boxes = []

#-----------------------------------------------------------------------------------------
